version: '3'
services:
  server:
    user: root
    build:
      context: .
      dockerfile: DockerfileDev
    environment:
      - NODE_ENV=development
      - GOOGLE_CLOUD_PROJECT=graphql-boilerplate
    volumes:
      - ./src/Server:/src/Server
      - ./src/dist:/src/dist
    command: npm run develop
    ports:
      - "4000:4000"