version: '3'
services:
  server:
    build:
      context: .
      dockerfile: DockerfileDev
    volumes:
      - ./src/Server:/src/Server
      - ./src/dist:/src/dist
    command: npm run develop
    ports:
      - "4000:4000"